### ISSUE TITLE
Built-in Distribution Reserved Keywords

### ISSUE THREAD

**Issue by akalicki** [alexandramedway/plt#12]
If we're going to add a few built-in distributions (normal, uniform, etc) as reserved keywords, we should add them as tokens to the scanner!

Distributions mentioned in the LRM:
 - uniform
 - normal
 - binomial
 - gamma

**Comment by lillyfwang** [comment]
Talked offline about this. Decided we were not going to make these distributions as keywords. They are part of your standard library and can be overridden.
